# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kerbility"
tagline: "not for your resume"
email: jwarner3412@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An assortment of KSP calculation tools and usefull things including satellite
  network calculator, and some kerboscript snippits.
baseurl: "/kerbility" # the subpath of your site, e.g. /blog
url: "https://jwarner3412.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: compressed

github_username: jwarner3412
